---
title: "Pertemuan 5 - MA,Arma,Arima"
author: "Ayyash"
output:
  html_document:
    theme: yeti
    toc: true
    toc_float: true
  word_document: default
  pdf_document: default
---


```{r}
set.seed(1234)
wn <- rnorm(300)
ts.plot(wn)
```

```{r}
set.seed(1234)
n <- 300
ma2 <- numeric(n)
ma2[1] <- wn[1]
ma2[2] <- wn[2] + 0.4 * wn[1]

for (i in 3:n) {
  ma2[i] <- wn[i] + 0.4 * wn[i - 1] + 0.6 * wn[i - 2]
}
head(ma2)
```

```{r}
ma2_sim <- arima.sim(list(order = c(0, 0, 2), ma = c(0.4, 0.6)), n = 300)
head(ma2_sim)
```

```{r}
ts.plot(ma2, main = "Time Series Plot MA(2) Manual")
```
```{r}
par(mfrow = c(1, 2))
acf(ma2, lag.max = 20, main = "ACF MA(2)")
pacf(ma2, lag.max = 20, main = "PACF MA(2)")
par(mfrow = c(1, 1))
```
```{r}
TSA::eacf(ma2)
```

```{r}
# Lag 1
yt_ma2 <- ma2[-1]
yt_1_ma2 <- ma2[-300]

# Lag 2
yt_ma2_l2 <- ma2[-c(1, 2)]
yt_2_ma2 <- ma2[-c(299, 300)]

# Lag 3
yt_ma2_l3 <- ma2[-c(1, 2, 3)]
yt_3_ma2 <- ma2[-c(298, 299, 300)]

par(mfrow = c(1, 3))
plot(y = yt_ma2, x = yt_1_ma2, main = "Yt vs Yt-1")
plot(y = yt_ma2_l2, x = yt_2_ma2, main = "Yt vs Yt-2")
plot(y = yt_ma2_l3, x = yt_3_ma2, main = "Yt vs Yt-3")
par(mfrow = c(1, 1))
```
```{r}
rho_ma2_theo <- ARMAacf(ma = c(0.4, 0.6), lag.max = 3)
rho_ma2_sample <- c(1, cor(yt_ma2, yt_1_ma2), cor(yt_ma2_l2, yt_2_ma2), cor(yt_ma2_l3, yt_3_ma2))

data.frame(
  Lag = 0:3,
  Teoritis = rho_ma2_theo,
  Sampel = rho_ma2_sample
)
```

```{r}
set.seed(1234)
ar2 <- numeric(n)
ar2[1] <- wn[1]
ar2[2] <- 0.5 * ar2[1] + wn[2]

for (i in 3:n) {
  ar2[i] <- 0.5 * ar2[i - 1] + 0.2 * ar2[i - 2] + wn[i]
}
head(ar2)
```

```{r}
ar2_sim <- arima.sim(list(order = c(2, 0, 0), ar = c(0.5, 0.2)), n = 300)
head(ar2_sim)
```

```{r}
ts.plot(ar2, main = "Time Series Plot AR(2) Manual")
```

```{r}
par(mfrow = c(1, 2))
acf(ar2, lag.max = 20, main = "ACF AR(2)")
pacf(ar2, lag.max = 20, main = "PACF AR(2)")
par(mfrow = c(1, 1))
```

```{r}
TSA::eacf(ar2)
```

```{r}
# Lag 1
yt_ar2 <- ar2[-1]
yt_1_ar2 <- ar2[-300]

# Lag 2
yt_ar2_l2 <- ar2[-c(1, 2)]
yt_2_ar2 <- ar2[-c(299, 300)]

# Lag 3
yt_ar2_l3 <- ar2[-c(1, 2, 3)]
yt_3_ar2 <- ar2[-c(298, 299, 300)]

par(mfrow = c(1, 3))
plot(y = yt_ar2, x = yt_1_ar2, main = "Yt vs Yt-1")
plot(y = yt_ar2_l2, x = yt_2_ar2, main = "Yt vs Yt-2")
plot(y = yt_ar2_l3, x = yt_3_ar2, main = "Yt vs Yt-3")
par(mfrow = c(1, 1))
```
```{r}
rho_ar2_theo <- ARMAacf(ar = c(0.5, 0.2), lag.max = 3)
rho_ar2_sample <- c(1, cor(yt_ar2, yt_1_ar2), cor(yt_ar2_l2, yt_2_ar2), cor(yt_ar2_l3, yt_3_ar2))

data.frame(
  Lag = 0:3,
  Teoritis = rho_ar2_theo,
  Sampel = rho_ar2_sample
)
```

```{r}
set.seed(1234)
arma22 <- numeric(n)
arma22[1] <- wn[1]
arma22[2] <- 0.5 * arma22[1] + wn[2] + 0.4 * wn[1]

for (i in 3:n) {
  arma22[i] <- 0.5 * arma22[i - 1] + 0.2 * arma22[i - 2] + wn[i] + 0.4 * wn[i - 1] + 0.6 * wn[i - 2]
}
head(arma22)
```
```{r}
arma22_sim <- arima.sim(list(order = c(2, 0, 2), ar = c(0.5, 0.2), ma = c(0.4, 0.6)), n = 300)
head(arma22_sim)
```
```{r}
ts.plot(arma22, main = "Time Series Plot ARMA(2,2) Manual")
```

```{r}
par(mfrow = c(1, 2))
acf(arma22, lag.max = 20, main = "ACF ARMA(2,2)")
pacf(arma22, lag.max = 20, main = "PACF ARMA(2,2)")
par(mfrow = c(1, 1))
```
```{r}
TSA::eacf(arma22)
```

```{r}
# Lag 1
yt_arma22 <- arma22[-1]
yt_1_arma22 <- arma22[-300]

# Lag 2
yt_arma22_l2 <- arma22[-c(1, 2)]
yt_2_arma22 <- arma22[-c(299, 300)]

# Lag 3
yt_arma22_l3 <- arma22[-c(1, 2, 3)]
yt_3_arma22 <- arma22[-c(298, 299, 300)]

par(mfrow = c(1, 3))
plot(y = yt_arma22, x = yt_1_arma22, main = "Yt vs Yt-1")
plot(y = yt_arma22_l2, x = yt_2_arma22, main = "Yt vs Yt-2")
plot(y = yt_arma22_l3, x = yt_3_arma22, main = "Yt vs Yt-3")
par(mfrow = c(1, 1))
```

```{r}
rho_arma22_theo <- ARMAacf(ar = c(0.5, 0.2), ma = c(0.4, 0.6), lag.max = 3)
rho_arma22_sample <- c(1, cor(yt_arma22, yt_1_arma22), cor(yt_arma22_l2, yt_2_arma22), cor(yt_arma22_l3, yt_3_arma22))

data.frame(
  Lag = 0:3,
  Teoritis = rho_arma22_theo,
  Sampel = rho_arma22_sample
)
```

